export default [
    {
        "id":0,
        "name":"Korky",
        "age":7,
        "img":"dog-korky.jpg",
        "race":"Aussiepom",
        "family_friendly":true
    },
    {
        "id":1,
        "name":"Raider",
        "age":5,
        "img":"dog-raider.jpg",
        "race":"Bugg",
        "family_friendly":false
    },
    {
        "id":2,
        "name":"Rocky",
        "age":12,
        "img":"dog-rocky.jpg",
        "race":"Greyhound",
        "family_friendly":false
    },
    {
        "id":3,
        "name":"Rocky",
        "age":3,
        "img":"dog-rocky2.jpg",
        "race":"Rat Terrier",
        "family_friendly":true
    },
    {
        "id":4,
        "name":"Tiber",
        "age":8,
        "img":"dog-tiber.jpg",
        "race":"Whippet",
        "family_friendly":false
    },
    {
        "id":5,
        "name":"Toby",
        "age":4,
        "img":"dog-toby.jpg",
        "race":"Collie",
        "family_friendly":true
    }
]